// 内置物种定义。每个物种包含生态参数、外形与营养级信息。
import type { SpeciesDef, TrophicLevel } from './types';

/** 各营养级配色，供食物网与生物本体共用 */
export const TROPHIC_COLORS: Record<TrophicLevel, string> = {
  producer: '#3fa86a',
  primary: '#2e8b8b',
  secondary: '#d08a36',
  apex: '#e8704a',
  decomposer: '#8a7a5c',
};

export const TROPHIC_LABELS: Record<TrophicLevel, string> = {
  producer: '生产者',
  primary: '初级消费者',
  secondary: '次级消费者',
  apex: '顶级捕食者',
  decomposer: '分解者',
};

export const SPECIES: Record<string, SpeciesDef> = {
  // —— 生产者 ——
  phytoplankton: {
    id: 'phytoplankton',
    name: '浮游植物',
    latin: 'Phytoplankton',
    trophic: 'producer',
    color: TROPHIC_COLORS.producer,
    shape: 'plankton',
    prey: [],
    energyGain: 3.5,
    maxEnergy: 40,
    moveSpeed: 0.25,
    sizeRange: [0.18, 0.3],
    lifespan: 90,
    reproductionThreshold: 32,
    reproductionCost: 14,
    circadian: 'both',
    habitat: 'water',
    pollutionTolerance: 0.85,
    description: '水中微小的光合生物，是整个食物网的基础，白天通过光合作用积累能量。',
  },
  watergrass: {
    id: 'watergrass',
    name: '水草',
    latin: 'Hydrilla',
    trophic: 'producer',
    color: '#4fb87a',
    shape: 'plant',
    prey: [],
    energyGain: 2.2,
    maxEnergy: 60,
    moveSpeed: 0,
    sizeRange: [0.8, 1.6],
    lifespan: 240,
    reproductionThreshold: 50,
    reproductionCost: 22,
    circadian: 'both',
    habitat: 'bottom',
    pollutionTolerance: 0.4,
    description: '扎根水底的植物，为水生动物提供氧气与栖息场所，夜间停止光合作用。',
  },

  // —— 初级消费者 ——
  zooplankton: {
    id: 'zooplankton',
    name: '浮游动物',
    latin: 'Zooplankton',
    trophic: 'primary',
    color: TROPHIC_COLORS.primary,
    shape: 'plankton',
    prey: ['phytoplankton'],
    energyGain: 12,
    maxEnergy: 30,
    moveSpeed: 0.7,
    sizeRange: [0.22, 0.36],
    lifespan: 70,
    reproductionThreshold: 24,
    reproductionCost: 10,
    circadian: 'both',
    habitat: 'water',
    pollutionTolerance: 0.6,
    description: '以浮游植物为食的微小动物，是连接生产者与鱼类的关键环节。',
  },
  minnow: {
    id: 'minnow',
    name: '小鱼',
    latin: 'Minnow',
    trophic: 'primary',
    color: '#7bb8c4',
    shape: 'fish',
    prey: ['zooplankton', 'phytoplankton'],
    energyGain: 16,
    maxEnergy: 55,
    moveSpeed: 2.4,
    sizeRange: [0.45, 0.7],
    lifespan: 120,
    reproductionThreshold: 44,
    reproductionCost: 18,
    circadian: 'diurnal',
    habitat: 'water',
    pollutionTolerance: 0.5,
    description: '群居小鱼，白天气味活跃地觅食浮游生物，夜间减速休息，是众多捕食者的猎物。',
  },
  snail: {
    id: 'snail',
    name: '螺蛳',
    latin: 'Viviparidae',
    trophic: 'decomposer',
    color: TROPHIC_COLORS.decomposer,
    shape: 'snail',
    prey: ['phytoplankton'],
    energyGain: 10,
    maxEnergy: 40,
    moveSpeed: 0.4,
    sizeRange: [0.32, 0.5],
    lifespan: 180,
    reproductionThreshold: 32,
    reproductionCost: 14,
    circadian: 'both',
    habitat: 'bottom',
    pollutionTolerance: 0.7,
    description: '在水底缓慢爬行，刮食藻类与腐殖质，扮演分解者的角色。',
  },
  firefly: {
    id: 'firefly',
    name: '萤火虫',
    latin: 'Lampyridae',
    trophic: 'primary',
    color: '#f2d96b',
    shape: 'insect',
    prey: ['phytoplankton'],
    energyGain: 9,
    maxEnergy: 28,
    moveSpeed: 1.6,
    sizeRange: [0.2, 0.32],
    lifespan: 60,
    reproductionThreshold: 22,
    reproductionCost: 9,
    circadian: 'nocturnal',
    nocturnalGlow: true,
    habitat: 'air',
    pollutionTolerance: 0.2,
    description: '夜行性昆虫，夜晚腹部发出荧光，是热带雨林场景的标志性生物，对污染极敏感。',
  },
  larva: {
    id: 'larva',
    name: '孑孓',
    latin: 'Mosquito larva',
    trophic: 'primary',
    color: '#b07a4a',
    shape: 'worm',
    prey: ['phytoplankton'],
    energyGain: 8,
    maxEnergy: 22,
    moveSpeed: 1.0,
    sizeRange: [0.2, 0.34],
    lifespan: 50,
    reproductionThreshold: 16,
    reproductionCost: 7,
    circadian: 'both',
    habitat: 'surface',
    pollutionTolerance: 0.95,
    description: '蚊子的幼虫，在污染富营养的水中大量繁殖，是水质恶化的指示生物。',
  },

  // —— 次级消费者 ——
  carp: {
    id: 'carp',
    name: '青鱼',
    latin: 'Mylopharyngodon',
    trophic: 'secondary',
    color: TROPHIC_COLORS.secondary,
    shape: 'fish',
    prey: ['minnow', 'snail', 'zooplankton'],
    energyGain: 22,
    maxEnergy: 90,
    moveSpeed: 2.0,
    sizeRange: [0.9, 1.3],
    lifespan: 200,
    reproductionThreshold: 72,
    reproductionCost: 30,
    circadian: 'diurnal',
    habitat: 'water',
    pollutionTolerance: 0.45,
    description: '体型较大的淡水鱼，捕食小鱼、螺蛳等，需要清洁的水源，污染中难以存活。',
  },
  dragonfly: {
    id: 'dragonfly',
    name: '蜻蜓幼虫',
    latin: 'Anisoptera nymph',
    trophic: 'secondary',
    color: '#9b6b3a',
    shape: 'insect',
    prey: ['zooplankton', 'minnow'],
    energyGain: 18,
    maxEnergy: 60,
    moveSpeed: 1.4,
    sizeRange: [0.4, 0.6],
    lifespan: 150,
    reproductionThreshold: 48,
    reproductionCost: 20,
    circadian: 'diurnal',
    habitat: 'water',
    pollutionTolerance: 0.35,
    description: '水中凶猛的捕食者，能捕食小型鱼类与浮游动物，对水质要求较高。',
  },
  leech: {
    id: 'leech',
    name: '水蛭',
    latin: 'Hirudinea',
    trophic: 'secondary',
    color: '#5a4636',
    shape: 'leech',
    prey: ['minnow', 'larva'],
    energyGain: 16,
    maxEnergy: 50,
    moveSpeed: 1.1,
    sizeRange: [0.4, 0.7],
    lifespan: 140,
    reproductionThreshold: 38,
    reproductionCost: 16,
    circadian: 'both',
    habitat: 'bottom',
    pollutionTolerance: 0.9,
    description: '耐污的环节动物，在污染水域中繁盛，吸附在猎物身上吸血。',
  },

  // —— 顶级捕食者 ——
  snakehead: {
    id: 'snakehead',
    name: '黑鱼',
    latin: 'Channa argus',
    trophic: 'apex',
    color: TROPHIC_COLORS.apex,
    shape: 'fish',
    prey: ['minnow', 'carp', 'dragonfly'],
    energyGain: 40,
    maxEnergy: 150,
    moveSpeed: 2.8,
    sizeRange: [1.3, 1.9],
    lifespan: 300,
    reproductionThreshold: 120,
    reproductionCost: 50,
    circadian: 'diurnal',
    habitat: 'water',
    pollutionTolerance: 0.55,
    description: '湖泊中的顶级掠食者，行动迅猛，捕食各种鱼类，位于食物链顶端。',
  },
  waterbird: {
    id: 'waterbird',
    name: '水鸟',
    latin: 'Aves aquatica',
    trophic: 'apex',
    color: '#d9d2c3',
    shape: 'bird',
    prey: ['minnow', 'carp'],
    energyGain: 34,
    maxEnergy: 120,
    moveSpeed: 3.2,
    sizeRange: [0.9, 1.3],
    lifespan: 260,
    reproductionThreshold: 95,
    reproductionCost: 40,
    circadian: 'diurnal',
    habitat: 'air',
    pollutionTolerance: 0.3,
    description: '在水面上空盘旋俯冲入水捕鱼的鸟类，清洁水体的象征，污染区域罕见。',
  },
};

export const SPECIES_LIST: SpeciesDef[] = Object.values(SPECIES);

/** 按营养级分组的物种 */
export const SPECIES_BY_TROPHIC: Record<TrophicLevel, SpeciesDef[]> = SPECIES_LIST.reduce(
  (acc, sp) => {
    acc[sp.trophic].push(sp);
    return acc;
  },
  {
    producer: [],
    primary: [],
    secondary: [],
    apex: [],
    decomposer: [],
  } as Record<TrophicLevel, SpeciesDef[]>,
);

/** 判断 predator 是否捕食 prey */
export function isPreyOf(predatorId: string, preyId: string): boolean {
  const predator = SPECIES[predatorId];
  return Boolean(predator && predator.prey.includes(preyId));
}

/** 获取某物种的捕食者物种 id 列表 */
export function getPredatorsOf(speciesId: string): string[] {
  return SPECIES_LIST.filter((sp) => sp.prey.includes(speciesId)).map((sp) => sp.id);
}
